### ISSUE TITLE
RE: Fading

### ISSUE THREAD

**Issue by jcpt928** [chadwpalm/HuePlex#11]
Is there, by chance, a way to modify the fade "time" between scenes? As of right now, they pretty much "pop" between scenes.

**Comment by chadwpalm** [comment]
This feature is already scheduled to be in the next development release. I'm hoping to have that version out this weekend. If you are using the develop tag for HuePlex you will see it there. I'll usually let it sit in development branch before putting it in the latest stable branch to work out any kinks.

Other features to look forward to:

- Scheduling. The ability to create a schedule for when the profiles will run at both the local and a global level.
- An option in the scene list to turn off the lights (since Hue makes this difficult in their app)
- Changed intervals and brightness into sliders from selection pull-downs in the server tab.
- Misc behind the scenes fixes

**Comment by chadwpalm** [comment]
@jcpt928 

This feature has been rolled out to the development branch and is included in the most recent develop tag in Docker Hub. Please feel free to test it and let me know if there are any issues/quirks. The latest should be v1.2.1 Build 56 as shown in the About screen.

**Comment by chadwpalm** [comment]
Scene fading has been incorporated into the new stable release v.1.2.2. Closing issue.

**Comment by jcpt928** [comment]
Awesome - meant to respond earlier. I'll get right on testing this as soon as I can.
