### ISSUE TITLE
Docker Crash adding Client

### ISSUE THREAD

**Issue by vderaa** [chadwpalm/HuePlex#17]
Trying to add a Client to HuePlex whilst using the docker image results in a crash.  The Docker Container then needs to be restarted.

I can use HuePlex natively, but haven't been able to install HuePlex as a service

**Comment by chadwpalm** [comment]
Could you supply the Docker logs at the point of when it crashes? Also, could you supply the method you used to start the container? If it was "docker run" can you supply the fully command, and if it was "docker-compose" can you supply the hueplex sections of the yaml file?

Also, what platform/OS are you running on?

Thanks.

**Comment by vderaa** [comment]
Hey!

Logs are below.  Looks like an issue connecting to plex to pull the Client details.
Docker command to run is:

sudo docker run -d --name=hueplex -e PUID=1000 -e PGID=1000 -e TZ=Europe/London -v /home/vdera/skylark/config/hueplex:/config -p 3939:3939 --restart unless-stopped chadwpalm/hueplex:latest

[nodemon] 2.0.22
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node ./bin/www`
[2023-08-05 18:41:00] [INFO]  Config file updated to UID: 1000 GID: 1000
[2023-08-05 18:41:00] [INFO]  Settings file read
[2023-08-05 18:41:00] [INFO]  Searching for bridges using mDNS
[8/5/2023 18:41:02] [INFO]  GET / - Status: 200
[8/5/2023 18:41:03] [INFO]  GET /static/js/main.a3e47b07.js - Status: 200
[8/5/2023 18:41:03] [INFO]  GET /static/css/main.6fa433e6.css - Status: 200
[2023-08-05 18:41:03] [INFO]  Settings file read
[8/5/2023 18:41:03] [INFO]  GET /backend/load - Status: 200
[8/5/2023 18:41:03] [INFO]  GET /static/media/loading-gif.803f24369a085e35482e.gif - Status: 200
[8/5/2023 18:41:03] [INFO]  GET /favicon.ico - Status: 200
[2023-08-05 18:41:05] [INFO]  Finished searching for bridges
[8/5/2023 18:41:06] [INFO]  GET /static/media/loading-gif.803f24369a085e35482e.gif - Status: 304
[2023-08-05 18:41:06] [INFO]  Retrieving Light Groups
[2023-08-05 18:41:06] [INFO]  Retrieving Light Scenes
[8/5/2023 18:41:16] [INFO]  POST /backend/client - Status: -
[2023-08-05 18:41:16] [ERROR] Could not connect to the Plex Server
/HuePlex/backend/client.js:82
        res.status(403).send(parser.xml2js(error.response.data, { compact: true, spaces: 4 }).errors.error._text);
                                                          ^

TypeError: Cannot read properties of undefined (reading 'data')
    at /HuePlex/backend/client.js:82:59
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /HuePlex/backend/client.js:70:3

Node.js v18.15.0
[nodemon] app crashed - waiting for file changes before starting...

**Comment by chadwpalm** [comment]
The error "Could not connect to the Plex Server" is slightly misleading as HuePlex technically never directly accesses your local Plex server. It gathers information from your Plex account via Plex's cloud API.

When you first start HuePlex it asks you to log into your Plex account. This is where HuePlex obtains a Plex token for HuePlex to connect to your account and stores that token in your HuePlex config (settings.js). I assume that you were able to log in since you had made it to the main screen of the app.

The section that is failing for you is when HuePlex tries to gather all the accounts that are authorized to access your server (besides your own). If it is successful, it will gather those accounts and send them to the UI. If there are no other accounts it just returns nothing but your own account. If it fails, it is usually either because the token is invalid, or because the token doesn't exist at all. (I need to fix the code that reports that)

The Docker crash is happening because it is supposed to be sending the reason for the error back to the UI, but apparently I need to fix that.....but the reason for the actual error is because it is having a problem retrieving the information from Plex it needs to move forward.

I also have to assume that since you were able to log into your Plex account when starting HuePlex that your server hosting HuePlex is connected to the internet properly. So we need to check that it actually retrieved a token and stored it into your config. Based on your command line, your settings file should be at: /home/vdera/skylark/config/hueplex

If it is difficult to understand the settings.js file, you can paste it into https://jsonformatter.org/ and that will format it better.

Could you check in that file for a "token" field and see if it is populated? (Don't paste it here, it is private). Then, if it is populated, go to a web browser and go to this URL to see if anything comes up: https://plex.tv/pms/friends/all?X-Plex-Token=<paste your token from Hueplex here>

**Comment by vderaa** [comment]
Hey Chad,

Yes, I managed to authenticate and I can see the HuePlex instance listed as an authorised device in the settings.
I've checked the settings.json file as suggested and after pasting the token into the plex URl, I do get a list of users on my server.  This list is identical to the settings.json file created if I install HuePlex natively.

If I use npm to spin up the native version, I'm able to set everything up, then use the same settings.josn file in the docker instance and everything works.  Of course if I try to add or edit a Client, it does crash again.

**Comment by chadwpalm** [comment]
> If I use npm to spin up the native version, I'm able to set everything up, then use the same settings.js file in the docker instance and everything works. Of course if I try to add or edit a Client, it does crash again.

Out of curiosity, have you tried spinning up the container with no settings file, allowing it to create a new settings.js file, log in to your account, then try and add a Client, all without copying the settings file from the native version, just to see if it still crashes?

I don't see how using the same Plex token for two different HuePlex instances would prevent the calling of the URL to fail, but I'd just like to see if that's the reason.

Thanks.

**Comment by chadwpalm** [comment]
My other theory is that it is not the Plex API that is failing, but Axios (the library that does the request) itself is failing.

I was wrong earlier.......when you log into Plex when first starting the app, it is all happening through the frontend (at the browser level) then pushing the token it retrieves to the settings file in the backend, so the ability to log into Plex does not necessarily imply that HuePlex can connect to the internet.

The point where it is crashing is actually the first time HuePlex tries to reach the outside world. This could actually be a case of the Docker container not being able to access the internet.

**Comment by vderaa** [comment]
I tried docker first.  The only reason I tried the native way of doing things was to see if it was just docker causing the issue.

I checked the docker network and the hueplex container is attached to bridge.

**Comment by chadwpalm** [comment]
Run your container this way and see if it fixes the problem:

sudo docker run -d --name=hueplex -e PUID=1000 -e PGID=1000 -e TZ=Europe/London -v /home/vdera/skylark/config/hueplex:/config -p 3939:3939 --network host --restart unless-stopped chadwpalm/hueplex:latest

**Comment by vderaa** [comment]
Yes!  That did it...thankyou!

**Comment by chadwpalm** [comment]
No problem. I'll update the documentation to try that parameter if the networking isn't working correctly. I've also added to my to-do list to fix the error reporting and prevent it from crashing the app.

**Comment by vderaa** [comment]
Thank you!  Do you have anywhere I can donate towards this?  Even if it just buys you a couple of beers/coffees? :)

**Comment by chadwpalm** [comment]
In the app, pull down the icon/menu on the top right and click "Donate". Appreciate it!

I took a short break from development because I worked non-stop to get it to where it is at today, but watch over the next few weeks for some more updates. Things always go to the develop branch and Docker tag first before rolling to the latest tag.

**Comment by vderaa** [comment]
I look forward to seeing what you can do!

Sent something your way, have a great day! :)
