### ISSUE TITLE
Issue with connection to online Plex account while requesting account info:  users.push is not a function

### ISSUE THREAD

**Issue by JonathanNet** [chadwpalm/HuePlex#21]
Getting this error while pressing the plus icon in clients

Issue with connection to online Plex account while requesting account info:  users.push is not a function

Using the lastest docker build

**Comment by chadwpalm** [comment]
This is an unusual error and the first time I've seen it. This is the section of code where it is retrieving your account information from Plex which is used to display you as one of the users during the Client creation. When you signed into HuePlex with your Plex account it should have created a Plex token for your account that associates with HuePlex.

It is unusual that Node JS is not seeing "users.push(temp);" as a callable function, unless something in the "temp" object is not right.

I'd like to see if you can manually retrieve the information and rule out if that's the problem. If you open the settings.js that was created (in the config directory you mounted), there should be a "token" tag. (I find it easier to paste the json into an online formatter). Once you have the token, open a browser and go to this url:

https://plex.tv/users/account?X-Plex-Token=<Plex Token>

The Plex Token should be pasted without quotes or brackets. Do you see the output of XML where the first line has information related to your account?

You said you are running latest docker build. 1.2.3 Main build 60, if you go to the About page, right? You must be, because that is where I added that particular log output.

Thanks
Chad

**Comment by JonathanNet** [comment]
HI again I tried the following thing with the token and did get alot of account info in xml.

**Comment by chadwpalm** [comment]
I'm unable to find a scenario where I can replicate your issue, so I created a custom Docker tag for you to test that has added debug code to help me try and figure out what the issue is. The image is: chadwpalm/hueplex:Jonathan-Test-1.2.3.65

I'd also like to get some more information to help me know the situation better:

1. Why type of platform are specifically running the Docker container on? (Intel/AMD based PC, NAS, Raspberry Pi, etc.)
2. Are you sure the version is 1.2.3.57? There should be no such thing on Docker Hub. The latest build should be 1.2.3.60. Build 57 was only used for 1.2.2. Ultimately, this shouldn't be the cause of the issue since none of the code for that particular section was updated between the two versions, but it still strikes me as odd.
3. Have you been using HuePlex for a while and it broke in the latest update, or are you a new user and haven't gotten it work yet? If you are a new user and you have no clients setup yet to lose, could I suggest deleting the settings.js file and restarting the Docker container? Perhaps something in the config got corrupted (though nothing in the config should cause this error, but just being thorough).
4. Since this issue is related to retrieving account information, is your account claimed to a Plex Server? This affects what information is retrieved. If you are a server admin it will retrieve information for accounts with access to your server to add to the user list. The debug log I added should show that.

If you could spin up the container with the tag I gave above and send me the logs at the point you press the plus icon on the Clients page, that would be great. Don't paste it here.....email it to me at chadwpalm@gmail.com. Though there is nothing sensitive in the log you probably don't want to have certain pieces of it shown to public.

Thanks,
Chad

**Comment by JonathanNet** [comment]
1. I am using Synology Nas, but also tried on Ubuntu 22.04 server but still the same.
2. Yeah I was copy/paste it from About
3. I am new into this addon, and I also try deleting settings.js, but still same error.
4. Yes I am claimed to be server admin

Il send the logs on email to you soon.

**Comment by chadwpalm** [comment]
Issue has been resolved.
